baseURL = 'https://xebialeestvoor.nl/'
title = 'Xebia - Leest voor'
summaryLength = 25
googleAnalytics = "G-7V776ZJ5H8"
copyright = "Xebia Nederland - All rights reserved"
enableEmoji = true
defaultContentLanguage = "nl"

[params]
  selfHosted = true
  lunrSearch = true
  previewCardImagePlacement = "top"
  logo = "/images/logo.png"
  description = "Elke eerste XKE van de maand wordt er voor gelezen."
