baseURL = 'https://xebialeestvoor.nl/'
languageCode = 'nl-nl'
title = 'Xebia - Leest voor'
summaryLength = 25
copyright = "Xebia Nederland - All rights reserved"
enableEmoji = true

[params]
  previewCardImagePlacement = "top"
  logo = "/images/logo.png"
  description = "Elke eerste XKE van de maand word er voor gelezen."

[params.social]
  github = "xebia"
  twitter = "xebia"
